### ISSUE TITLE
choose project name

### ISSUE THREAD

**Issue by sameoldmadness** [sameoldmadness/bem-starter-pack#10]
- bem-boilerplate
- opinionated-bem
- bem-starter-pack
- bem-jumpstart
- blinkered-bem

**Comment by veged** [comment]
blinkered-bem :+1:

**Comment by sameoldmadness** [comment]
please rename repo to blinkered-bem

**Comment by sbmaxx** [comment]
https://slovari.yandex.ru/blinkered/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4

**Comment by sameoldmadness** [comment]
@sbmaxx It's a feature.

**Comment by veged** [comment]
@sameoldmadness done! also transfer it to you ;-)
